make required check fails when build fails (#248)
* make required check fails when build fails

Unless forced to run with `success()` or `failure()`, the `success` job will be skipped, which is then interpreted as "can merge" by Github for some reason.

Add an explicit failing test to fix this broken behavior.

* make sure the check is always run

It appears that if one job in the matrix fails, the result will be "cancelled" instead. So we have to detect that case too.

* respect cancellation in build

This job's `always()` conditional makes it ignore cancellation request,
so we fix it by adding an explicit `cancelled()` check.

* print a message when a previous job failed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -47,7 +47,7 @@ jobs:
     #
     # The always() function here is required for the job to always run despite
     # what Github docs said, see: https://github.com/actions/runner/issues/491
-    if: always() && needs.changes.outputs.src != 'false'
+    if: always() && !cancelled() && needs.changes.outputs.src != 'false'
 
     strategy:
       fail-fast: false
@@ -111,8 +111,12 @@ jobs:
   # Set check-required on this
   success:
     needs: build
+    if: always()
     runs-on: ubuntu-latest
     name: 'All check passes'
     steps:
-      - run: |
-          echo "This is a workaround for Github's broken software"
+      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        name: 'Fail when previous jobs fails'
+        run: |
+          echo "::error::One of the previous jobs failed"
+          exit 1
