make required check fails when build fails
Unless forced to run with `success()` or `failure()`, the `success` job will be skipped, which is then interpreted as "can merge" by Github for some reason.

Add an explicit failing test to fix this broken behavior.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -111,8 +111,12 @@ jobs:
   # Set check-required on this
   success:
     needs: build
+    if: success() || failure()
     runs-on: ubuntu-latest
     name: 'All check passes'
     steps:
-      - run: |
-          echo "This is a workaround for Github's broken software"
+      - if: contains(needs.*.result, 'failure')
+        name: 'Fail when previous jobs fails'
+        run: |
+          echo "::error"
+          exit 1
